#!/usr/bin/env python
"""
Данный скрипт подключается к серверу Asterisk, получает ip адреса SIP клиентов,
далее, по SSH подключаемся к этим ip и отправляем команду чистки пользовательских
данных и перезагружаем телефон
"""
import paramiko
import time
import os
import re

user_asterisk = 'user_asterisk'
password_asterisk = 'password_asterisk'
asterisk_ip  = 'asterisk_ip'

user_phone = 'user_phone'
password_phone = 'password_phone'

def connect_ssh(user, password, host):
    """Подключаемся к клиенту по SSH"""
    try:
        client = paramiko.SSHClient()
        client.set_missing_host_key_policy(paramiko.AutoAddPolicy())
        client.connect(hostname=host, username=user, password=password,
                    look_for_keys=False, allow_agent=False)

        return client
    except:
        print('Connection error')

def get_ip():
    """Подлключаемся по SSH и получаем список ip"""
    try:
        with connect_ssh(user_asterisk, password_asterisk, asterisk_ip).invoke_shell() as ssh:
            ssh.send('asterisk -r\n')
            time.sleep(1)
            ssh.send('sip show peers\n')
            time.sleep(2)
            result = ssh.recv(50000).decode('utf-8')
            print(result)
            ip = re.findall(r'\d{2}\.\d{2}\.\d{2}?\.[1]\d{2}', result)

            print('IP получены')
            print('Всего: ' + str(len(ip)))
            return ip
    except:
        print('Command get ip error')

def command_reboot(host):
    """Подключаемся по SSH и отправляем команду перезагрузки"""
    try:
        with connect_ssh(user_phone, password_phone, host).invoke_shell() as ssh:
            ssh.send('format mode\n')
            time.sleep(1)
            ssh.send('Y\n')
            time.sleep(2)

            result = ssh.recv(50000).decode('utf-8')
            print(result)
    except:
        print('Command reboot error')

for i in get_ip():
    command_reboot(i)
